// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"screenTint","status":true,"description":"Allows screen tinting with plugin commands.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}}
];
